### ISSUE TITLE
update to asciidoctor 1.5.6

### ISSUE THREAD

**Issue by jagedn** [asciidoctor/asciidoctorj-pdf#14]
Rigth now build.gradle is using by default 1.5.5 but version 1.5.6 was released few months ago

`asciidoctorJVersion = project.hasProperty('asciidoctorJVersion') ? project.asciidoctorJVersion : '1.5.5' `

**Comment by mojavelinux** [comment]
As far as I understand it, that version is only for testing. This jar does not bundle Asciidoctor or AsciidoctorJ. You should be able to use this jar with any version of AsciidoctorJ.

**Comment by robertpanzer** [comment]
Yes, this is only for testing.
It's not even a dependency anymore in the latest version so that you should not even fall accidentally down to an old version of Asciidoctor.
However we'd like to maintain compatibility with this version of AsciidoctorJ.

Tests with newer versions of AsciidoctorJ happen in the asciidoctor/asciidoctorj.

**Comment by mojavelinux** [comment]
Perfect!
